---
- name: "Provision Image"
  hosts: default
  become: true
  tasks:
    - name: Install Java, Python, fontconfig
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - default-jdk
        - fontconfig
        - python3
    - name: Add jenkins signing key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    - name: Add Jenkins Repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: latest
        update_cache: yes
    - name: Start Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes
